# Generated by Django 5.0.4 on 2024-04-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_prive',
            new_name='event_price',
        ),
    ]
